### ISSUE TITLE
S3 Read Speed and Error

### ISSUE THREAD

**Issue by tqchen** [dato-code/SFrame#153]
I encountered some error when loading a big sframe directly from s3 and do processing. This error disappear after I directly download from S3, so I guess there might be some problem in current S3 reading API.

opened a issue to track this as discussed with @ylow

**Comment by ylow** [comment]
We use a modified dmlc::io reader internally for S3 reading. https://github.com/dmlc/dmlc-core/pull/68 might be relevant.

**Comment by ylow** [comment]
Regarding performance, the current architecture in SFrame is to seek, download a block and cache that on local disk. Then future reads of the same block should go straight from local disk. (block size is set to a few MB I think). However due to file handle locking, it is possible that only one S3 read is issued at any one time resulting in decreased performance. 

This will be a much deeper optimization since this performance limitation also applies to parallel reading from a single local file (say on an SSD) where we lock the entire file handle to perform the seek. 

In these cases, the optimization can be performed simply by just opening multiple handles to same file. However, this must be done carefully since it is easy to exceed the maximum number of file handles allowed by the system. (For instance, OS X default is 256)

**Comment by haijieg** [comment]
The read error on large file should be fixed by https://github.com/dato-code/SFrame/pull/316.

**Comment by hoytak** [comment]
Closing issue unless there are more problems.
