### ISSUE TITLE
Sframe at the limit

### ISSUE THREAD

**Issue by arita291** [dato-code/SFrame#251]
Hi,

What is the maximum size for Sframe csv ?
What is the maximum size used for Sframe ? (10 Terabytes, ok ?)

**Comment by esamanas** [comment]
We've demonstrated up to 1 TB, which was the size of the dataset before it was parsed. We can't really give a definitive answer to this question. It depends on how much free disk space you have and how well the data you are loading compresses. If you have over 10 TB of free space, then you should be able to load a 10 TB CSV for example. If you can't, report a bug and we'll fix it.

**Comment by arita291** [comment]
Hi,

Disk space does not matter since If I have a 1To file, it means I cam store it....

The key point is actual RAM:

with 1To disk file, how much in RAM is taking ?

with 10To disk file, how much RAM is using ?






On 08 Apr 2016, at 06:04, Evan Samanas <notifications@github.com> wrote:

We've demonstrated up to 1 TB, which was the size of the dataset before it was parsed. We can't really give a definitive answer to this question. It depends on how much free disk space you have and how well the data you are loading compresses. If you have over 10 TB of free space, then you should be able to load a 10 TB CSV for example. If you can't, report a bug and we'll fix it.

―

**Comment by dbickson** [comment]
Hi
Please ask your question in our user forum: http://forum.dato.com - it is the best place to ask such questions.

**Comment by esamanas** [comment]
I said FREE disk space. Yes the file is on your disk, but SFrame has its own data format that it copies an original data file in to. We don't modify your original.

For both it should be the same amount of RAM, which would be as much as you allow it. I believe the setting is currently at half of what's on your machine. For the rest, we spill to disk, which is why free disk space is important.  The setting for how much RAM is taken up can be viewed by calling: 

`sframe.get_runtime_config`

The setting is called `GRAPHLAB_FILEIO_MAXIMUM_CACHE_CAPACITY`.  You can set this to something different by providing that string to the `sframe.set_runtime_config` function.
