### ISSUE TITLE
Reduce disk utilization

### ISSUE THREAD

**Issue by malmaud** [dato-code/SFrame#72]
I notice that the SFrame folder comes in at a sizable 5.5Gb after compiling libunity. I'm interested in extracting the minimum runtime dependencies of libunity plus the header files, something like what `make install` would do for many packages.

Is that (or is there a plan to) make that functionality available? Or it's not too much trouble, would you mind offering me some guidance on how to do it manually? 

Thanks!

**Comment by ylow** [comment]
Ah. It is huge mainly because of symbol tables. stripping it brings it substantially smaller. (Also, we static link most things).

We do collect an "SDK" during the build process which is just the minimal set of header files required.
 - Make in [build]/oss_src/unity
 - [build]/oss_src/unity/sdk will now contain a complete subdirectory of headers, a sample Makefile, etc.
 - And you want the core library in [build]oss_src/unity/libunity_shared.so/dylib/dll

**Comment by znation** [comment]
@ylow Do we plan to take any action in the SFrame repo to reduce the size of built artifacts?
