### ISSUE TITLE
Iterate on different chunks of a sframe

### ISSUE THREAD

**Issue by sb2nov** [dato-code/SFrame#84]
Hi, I'm trying to do iterate over a large sframe to do something like example below
```
import sframe

def transform(x):
    print x

sf = sframe.SFrame()
sf['a'] = [1, 1, 1, 1, 2, 2, 2, 3, 4, 4, 5]
sf['b'] = [1, 2, 1, 2, 3, 3, 1, 4, None, 2, 3]

for r in sf:
    for x in r:
        transform(x)
```

Is there a way to use multiprocessing to run something like this, when I try to chunk the sframe I get the same issue mentioned on the [forums here](http://forum.dato.com/discussion/637/how-to-use-multiprocessing-with-graphlab-create)

**Comment by esamanas** [comment]
I may be confused as to what you're asking, but can't SFrame.apply or SArray.apply be used for this? Apply chunks the SFrame and runs the transform function in parallel automatically.

**Comment by sb2nov** [comment]
I'm trying to export the sframe into avro dumps. To make it faster I was trying to use multiprocessing and ran into the issue mentioned above. When using the apply method I see the following error:

test case:
```import csv
import sframe

RECORD = 0
FILE_ID = 0
FILE = open(str(FILE_ID), 'wb')
WRITER = csv.writer(FILE)


def transform(x):
    global FILE
    global RECORD
    global FILE_ID
    global WRITER

    if (RECORD % 2) == 0 and RECORD > 1:
        FILE_ID += 1
        FILE.close()
        FILE = open(str(FILE_ID), 'wb')
        WRITER = csv.writer(FILE)

    print x, RECORD, FILE_ID
    WRITER.writerow([x])
    RECORD += 1


def transform_row(r):
    print r
    for x in r:
        transform(x)
    print 'row end'


sf = sframe.SFrame()
sf['a'] = [1, 1, 1, 1, 2, 2, 2, 3, 4, 4, 5]
sf['b'] = [1, 2, 1, 2, 3, 3, 1, 4, None, 2, 3]

sf.apply(transform_row)
FILE.close()
```

error:
```
Traceback (most recent call last):
  File "partition.py", line 38, in <module>
    sf.apply(transform_row)
  File "/Users/sbajaj/miniconda/lib/python2.7/site-packages/sframe/data_structures/sframe.py", line 2591, in apply
    return SArray(_proxy=self.__proxy__.transform(fn, dtype, seed))
  File "/Users/sbajaj/miniconda/lib/python2.7/site-packages/sframe/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
pickle.PicklingError: Can't pickle builtin <type 'member_descriptor'>
```

Any advice on what I'm doing wrong would be great.

**Comment by esamanas** [comment]
First, when you apply (or iterate) over an SFrame, the value is passed to the function as a python dictionary, so you're only writing the column name in your code.

But a more fundamental problem with this is that lambda workers aren't meant to be able to share state like this...each worker gets its own copy of the data captured by the closure of the function. As far as I know the results will be undefined. Even if they were, there's no locks guarding the global variables. A way you could do something like this is to write as many files as there are lambda workers, but to do that you'd need a reliable way to figure out which lambda worker you are and write to the correct file. We don't explicitly expose this, but it's possible to hack something...perhaps based on PID since this is all on one machine. An oddity could be that lambdas are allowed to crash and restart.

In any case though, have you tried saving your data as Avro in a serial fashion? Was that too slow? I could see gaining speed by parallelizing the conversion for sure, but unless you have a parallel file system you won't see great gains on the actual I/O. To get parallelization MAYBE you could have the lambda workers just run the conversion to Avro format and return the bytes as a string, and then save the resulting SFrame as a CSV with one column (use the save function on SFrame). 

The real way to do this would be to write an Avro writer on the C++ side using Avro's C++ library :).

**Comment by sb2nov** [comment]
The dictionary case was just some mock example I created but isn't the actual code. Coming back to the issue at hand.

Yeah the serial writing along with the transformation code took several hours which was quite slow compared to the rest of the processing pipeline. I was originally trying to just iterate over the pipeline in parallel and then have each worker write to its own file which would be fine if I was using the multiprocessing workers but that would not work with lambda workers like you mentioned as I don't know which worker is which without sharing a global state. 

I will try the transform in parallel and the write in serial order for now try to see the performance implications first, otherwise fall back to the C++ alternative. Can you point me to an example in the sframe code on how do to it on the C++ side ?

**Comment by esamanas** [comment]
Here's our CSV writer:
https://github.com/dato-code/SFrame/blob/master/oss_src/sframe/csv_writer.cpp

And here's how we use the Avro library for the reader:
https://github.com/dato-code/SFrame/blob/master/oss_src/sframe/generic_avro_reader.cpp

**Comment by sb2nov** [comment]
Thanks for all the help, I'll close the issue for now.
